add workflows release
kuasar-io/kuasar pull request #95
Opened 2023-09-15 07:40 UTC by dierbei

Fix #81

2023-09-23 09:50 UTC, xiaods commented
why not merged it?

2023-09-23 09:51 UTC, xiaods commented
suggest squash commit to one commit. give more context on your commit log.

2023-09-23 10:12 UTC, Burning1020 commented
> suggest squash commit to one commit. give more context on your commit log.

@dierbei Yes, please squash your commits, thanks.

2023-09-23 10:54 UTC, dierbei commented
Thanks for the suggestion. Wait a minute, I still need to make some adjustments.

2023-09-25 11:59 UTC, dierbei commented
@Burning1020 @xiaods Already rebase. please help me to review, thanks.

2023-09-26 11:12 UTC, Burning1020 commented on .github/workflows/release.yaml
> +          EOL
How about touch a containerd file and copy it in `Makefile`

2023-09-26 11:12 UTC, Burning1020 commented on .github/workflows/release.yaml
> +        run: RUNTIME=docker make bin/kuasar.img
Add `sudo` to here, refer to: https://github.com/kuasar-io/kuasar/blob/main/.github/workflows/ci.yml#L76

2023-09-26 11:12 UTC, Burning1020 commented on .github/workflows/release.yaml
> +          cp -r ./* ../temp/
We should provide a package that contains all vendor source code, so we need use `cargo vendor`  to generate all vendor codes under every cargo folders.

2023-09-26 11:12 UTC, Burning1020 commented on .github/workflows/release.yaml
> +      - vmlinux-bin
We have `vmm quark wasm` target in Makefile. Maybe `make vmm`, `make quark` and `make wasm` could make it simple.

2023-10-08 08:15 UTC, Burning1020 requested changes

2023-10-08 08:15 UTC, Burning1020 commented on scripts/build/gen-containerd-config.sh
> +sudo mkdir bin && sudo tar -C bin -xzvf containerd-1.7.0-linux-amd64.tar.gz
```shell
git clone https://github.com/kuasar-io/containerd.git
make -C containerd bin/containerd
mkdir bin && mv containerd/bin/containerd bin
```

2023-10-08 08:15 UTC, Burning1020 commented on scripts/build/gen-containerd-config.sh
> +
Add filehead and `set -e`:https://github.com/kuasar-io/kuasar/blob/main/examples/run_example_container.sh#L2-L16

2023-10-08 08:15 UTC, Burning1020 commented on scripts/build/gen-containerd-config.sh
> +sudo tee bin/config.toml > /dev/null <<EOF
Is it necessary to add `sudo` in front of every commands? I mean it is possiable to add it in `job.step.run`, https://github.com/kuasar-io/kuasar/pull/95#discussion_r1337032458

2023-10-09 02:29 UTC, Burning1020 commented on scripts/build/download-containerd.sh
> +mkdir bin && make -C containerd bin/containerd && mv containerd/bin/containerd bin
Append `rm -rf containerd`, we need to cleanup.

2023-10-10 07:34 UTC, Burning1020 commented on .github/workflows/release.yaml
> +        run: sudo -E ./scripts/build/download-containerd.sh
`build-containerd.sh`, not `donwload-containerd.sh`

2023-10-11 09:05 UTC, Burning1020 approved these changes
LGTM. Well done.

2023-10-11 09:08 UTC, merged